# -*- coding: utf-8 -*-
#!/usr/bin/env python
from sqlalchemy import Column, String, create_engine, VARCHAR, DATETIME, DECIMAL, TIMESTAMP, DATE
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
engine = create_engine('mysql+mysqlconnector://root:011291@localhost:3306/drf')
DBSession = sessionmaker(bind=engine)
session = DBSession()

class drfOpsClassBase(Base):
    __tablename__ = 'drf_ops_class_base'#班次表
    base_id = Column(VARCHAR(32), nullable=False, primary_key=True)
    class_id = Column(VARCHAR(32))
    receive_time = Column(VARCHAR(8))
    send_time = Column(VARCHAR(8))
    duty_officer = Column(VARCHAR(32))
    drf_monitor = Column(VARCHAR(32))
    receive_well_depth = Column(DECIMAL(8, 2))
    send_well_depth = Column(DECIMAL(8, 2))
    backfill_well_depth = Column(DECIMAL(8, 2))
    backfill_type = Column(VARCHAR(32))
    drilled_footage = Column(DECIMAL(8, 2))#进尺
    fen_well_depth = Column(DECIMAL(8, 2))
    drillrig_group_size = Column(VARCHAR(500))
    bit_model = Column(VARCHAR(32))
    bit_size = Column(VARCHAR(32))
    delivery_volume = Column(DECIMAL(32))
    pump_pressure = Column(DECIMAL(8, 2))
    torque = Column(DECIMAL(8, 2))
    side_well_depth = Column(DECIMAL(8, 2))
    backfill_start_depth = Column(DECIMAL(8, 2))
    backfill_end_depth = Column(DECIMAL(8, 2))
    well_side = Column(VARCHAR(35))
    position = Column(VARCHAR(35))
    fluid_heat = Column(DECIMAL(8, 2))
    fluid_volume = Column(DECIMAL(8, 2))
    add_water_volume = Column(DECIMAL(8, 2))
    sampling_depth = Column(DECIMAL(8, 2))
    solidoid_content = Column(DECIMAL(8, 2))
    amargosite_content = Column(DECIMAL(8, 2))
    layer_lithology = Column(VARCHAR(32))
    layer_position = Column(VARCHAR(32))
    int_note = Column(VARCHAR(500))
    join_note = Column(VARCHAR(500))
    spare1 = Column(VARCHAR(32))
    spare2 = Column(VARCHAR(32))
    spare3 = Column(VARCHAR(32))
    spare4 = Column(VARCHAR(32))
    create_org_id = Column(VARCHAR(32))
    create_date = Column(DATETIME)
    modify_date = Column(DATETIME)
    creator_id = Column(VARCHAR(32))
    rflag = Column(VARCHAR(1))
    isondata = Column(VARCHAR(1), default='0')
    layer_lithology_name = Column(VARCHAR(100))
    layer_position_name = Column(VARCHAR(100))
    well_level = Column(VARCHAR(100))
    con_well_section = Column(VARCHAR(100))
    drf_type_name = Column(VARCHAR(100))
    drf_type = Column(VARCHAR(32))
    bit_model_name = Column(VARCHAR(100))
    bit_size_name = Column(VARCHAR(100))
    rig_type = Column(VARCHAR(20))
    casing_depth = Column(DECIMAL(8, 2))

class drfOpsClass(Base):
    __tablename__ = 'drf_ops_class'
    class_id = Column(VARCHAR(32), nullable=False, primary_key=True)
    task_id = Column(VARCHAR(32))
    work_date = Column(DATE, default='0000-00-00')
    class_order = Column(VARCHAR(32))
    spare1 = Column(VARCHAR(32))
    spare2 = Column(VARCHAR(32))
    spare3 = Column(VARCHAR(32))
    spare4 = Column(VARCHAR(32))
    create_org_id = Column(VARCHAR(32))
    create_date = Column(DATETIME)
    modify_date = Column(DATETIME)
    creator_id = Column(VARCHAR(32))
    rflag = Column(VARCHAR(1))
    isondata = Column(VARCHAR(1), default='0')